before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - format_overrides:
      - goos: windows
        format: zip
release:
  github:
  prerelease: auto
dockers:
  - image_templates:
    - "ghcr.io/pellared/seed/{{ .ProjectName }}:latest"
    - "ghcr.io/pellared/seed/{{ .ProjectName }}:{{ .Major }}"
    - "ghcr.io/pellared/seed/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/pellared/seed/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
